# Generated by Django 2.2.4 on 2020-05-02 23:59

from django.db import migrations


def copy_complaints_to_flat_complaints(apps, schema_editor):
    Complaint = apps.get_model('property', 'Complaint')
    FlatComplaint = apps.get_model('property', 'FlatComplaint')

    for complaint in Complaint.objects.all():
        FlatComplaint.objects.get_or_create(
            author=complaint.owner,
            flat=complaint.flat,
            text=complaint.text,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200503_0258'),
    ]

    operations = [
        migrations.RunPython(copy_complaints_to_flat_complaints)
    ]
