# Generated by Django 2.2.4 on 2020-05-03 00:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0009_auto_20200503_0303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlatComplaint',
            new_name='Complaint',
        ),
    ]
