# Generated by Django 3.0.5 on 2020-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20200507_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats_in_property',
            field=models.ManyToManyField(related_name='flats_in_property', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
