# Generated by Django 3.0.5 on 2020-05-07 16:44

from django.db import migrations


def copy_from_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phonenumber=flat.owner_phone_pure,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200507_1922'),
    ]

    operations = [
        migrations.RunPython(copy_from_flat_to_owner)
    ]
